$(document).ready(function(){
	console.log("hiyaaa.");

	$(".h1").hover(function(){
		$(".h1").toggleClass("a1");
	})
	$(".h2").hover(function(){
		$(".h2").toggleClass("a2");
	})
	$(".h3").hover(function(){
		$(".h3").toggleClass("a3");
	})
	$(".h4").hover(function(){
		$(".h4").toggleClass("a4");
	})
	$(".h5").hover(function(){
		$(".h5").toggleClass("a5");
	})
	$(".h6").hover(function(){
		$(".h6").toggleClass("a6");
	})
	$(".h7").hover(function(){
		$(".h7").toggleClass("a7");
	})
	$(".h8").hover(function(){
		$(".h8").toggleClass("a8");
	})
	$(".h9").hover(function(){
		$(".h9").toggleClass("a9");
	})
	$(".h10").hover(function(){
		$(".h10").toggleClass("a10");
	})
	$(".h11").hover(function(){
		$(".h11").toggleClass("a11");
	})
	$(".h12").hover(function(){
		$(".h12").toggleClass("a12");
	})
	$(".h13").hover(function(){
		$(".h13").toggleClass("a13");
	})
	$(".h14").hover(function(){
		$(".h14").toggleClass("a14");
	})
	$(".h15").hover(function(){
		$(".h15").toggleClass("a15");
	})
	$(".h16").hover(function(){
		$(".h16").toggleClass("a16");
	})
	$(".h17").hover(function(){
		$(".h17").toggleClass("a17");
	})
	$(".h18").hover(function(){
		$(".h18").toggleClass("a18");
	})
	$(".h19").hover(function(){
		$(".h19").toggleClass("a19");
	})
	$(".h20").hover(function(){
		$(".h20").toggleClass("a20");
	})
	$(".h21").hover(function(){
		$(".h21").toggleClass("a21");
	})
	$(".h22").hover(function(){
		$(".h22").toggleClass("a22");
	})
	$(".h23").hover(function(){
		$(".h23").toggleClass("a23");
	})
	$(".h24").hover(function(){
		$(".h24").toggleClass("a24");
	})
	$(".h25").hover(function(){
		$(".h25").toggleClass("a25");
	})
	$(".h26").hover(function(){
		$(".h26").toggleClass("a26");
	})
	$(".h27").hover(function(){
		$(".h27").toggleClass("a27");
	})
	$(".h28").hover(function(){
		$(".h28").toggleClass("a28");
	})
	$(".h29").hover(function(){
		$(".h29").toggleClass("a29");
	})
	$(".h30").hover(function(){
		$(".h30").toggleClass("a30");
	})
	$(".h31").hover(function(){
		$(".h31").toggleClass("a31");
	})
	$(".h32").hover(function(){
		$(".h32").toggleClass("a32");
	})
	$(".h33").hover(function(){
		$(".h33").toggleClass("a33");
	})
	$(".h34").hover(function(){
		$(".h34").toggleClass("a34");
	})
	$(".h35").hover(function(){
		$(".h35").toggleClass("a35");
	})
	$(".h36").hover(function(){
		$(".h36").toggleClass("a36");
	})
	$(".h37").hover(function(){
		$(".h37").toggleClass("a37");
	})
	$(".h38").hover(function(){
		$(".h38").toggleClass("a38");
	})
	$(".h39").hover(function(){
		$(".h39").toggleClass("a39");
	})
	$(".h40").hover(function(){
		$(".h40").toggleClass("a40");
	})
	$(".h41").hover(function(){
		$(".h41").toggleClass("a41");
	})
	$(".h42").hover(function(){
		$(".h42").toggleClass("a42");
	})
	$(".h43").hover(function(){
		$(".h43").toggleClass("a43");
	})
	$(".h44").hover(function(){
		$(".h44").toggleClass("a44");
	})
	$(".h45").hover(function(){
		$(".h45").toggleClass("a45");
	})
	$(".h46").hover(function(){
		$(".h46").toggleClass("a46");
	})
	$(".h47").hover(function(){
		$(".h47").toggleClass("a47");
	})
	$(".h48").hover(function(){
		$(".h48").toggleClass("a48");
	})
	$(".h49").hover(function(){
		$(".h49").toggleClass("a49");
	})
	$(".h50").hover(function(){
		$(".h50").toggleClass("a50");
	})
	$(".h51").hover(function(){
		$(".h51").toggleClass("a51");
	})
	$(".h52").hover(function(){
		$(".h52").toggleClass("a52");
	})
	$(".h53").hover(function(){
		$(".h53").toggleClass("a53");
	})
	$(".h54").hover(function(){
		$(".h54").toggleClass("a54");
	})
	$(".h55").hover(function(){
		$(".h55").toggleClass("a55");
	})
	$(".h56").hover(function(){
		$(".h56").toggleClass("a56");
	})
	$(".h57").hover(function(){
		$(".h57").toggleClass("a57");
	})
	$(".h58").hover(function(){
		$(".h58").toggleClass("a58");
	})
	$(".h59").hover(function(){
		$(".h59").toggleClass("a59");
	})
	$(".h60").hover(function(){
		$(".h60").toggleClass("a60");
	})
})